[Unit]
Description=Debian Server Dashboard
After=network.target

[Service]
# Run the dashboard as your account
User=daki

# Folder containing main.py
WorkingDirectory=/home/daki/debian_server_dashboard

# Use your project's Python to start Uvicorn
ExecStart=/home/daki/server_dasboard/.venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port 8000

# If the app crashes, wait five seconds and try again
Restart=on-failure
RestartSec=5

[Install]
# Allow this service to start during normal system startup
WantedBy=multi-user.target
